apiVersion: apps/v1
kind: Deployment
metadata:
  name: sancicd
spec:
  selector:
    matchLabels:
      app: sancicd
      tier: sancicd
      track: stable
  template:
    metadata:
      labels:
        app: sancicd
        tier: sancicd
        track: stable
    spec:
      containers:
        - name: sancicd
          image: "sancicd:test"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sancicd
spec:
  type: NodePort
  selector:
    app: sancicd
    tier: sancicd
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
    nodePort: 30000